### Historical Context
The Church of Christ emerged from the American Restoration Movement, aiming to restore New Testament practices. Preachers were seen as pro-claimers of the gospel, not a separate clergy class, aligning with the movement's rejection of denominational hierarchies.

### Evolution of the Role
Initially, preaching was often done by traveling ministers, but over time, congregations began hiring full-time preachers, especially after World War II. This shift faced controversy, with some advocating for mutual ministry by all capable men, reflecting ongoing debates about structure.

The origin of preachers in the Church of Christ can be traced to the New Testament model of evangelists and ministers, as interpreted by key figures in the Restoration Movement. Leaders such as Alexander Campbell and Barton W. Stone were instrumental in shaping this role. Campbell, for instance, began preaching without a salary in 1810 and was known for his debates and publications, such as the *Christian Baptist* and *Millennial Harbinger*, which gave voice to the movement [Alexander Campbell | Founder of Disciples of Christ, Reformer, Educator | Britannica](https://www.britannica.com/biography/Alexander-Campbell-American-clergyman). Stone similarly contributed through his preaching, emphasizing apostolic Christianity.

The movement rejected formal clergy structures, aligning with the principle of the priesthood of all believers. This is evident in the lack of formal ordination for preachers, with some legally ordained by elders only for state requirements, such as performing marriages [Disciples Historical Society: Churches of Christ](https://discipleshistory.org/wiki/churches-of-christ/). Instead, preachers were seen as members called to proclaim the gospel, based on New Testament roles like those mentioned in Ephesians 4:11 (apostles, prophets, evangelists, pastors, teachers).
#### Early Practices and Itinerant Preaching
In the early days, preaching was often conducted by itinerant ministers who traveled between congregations. This practice is reflected in the lives of Campbell and Stone, who engaged in extensive preaching tours to spread their message. The *Disciples Historical Society* notes that there was initial opposition to located preachers—those employed full-time by one congregation—particularly in the 1880s, with figures like Austin McGary and David Lipscomb advocating against this [Disciples Historical Society: Churches of Christ](https://discipleshistory.org/wiki/churches-of-christ/). This resistance stemmed from a desire to maintain mutual ministry, where all capable men in the congregation shared preaching responsibilities, with about 130 congregations emphasizing this approach today.

#### Evolution and Controversy
The role of preachers evolved significantly over time. Not until the early 20th century did some churches appoint ministers to do most of the preaching, and many did not employ preachers until after World War II, according to historical accounts [Disciples Historical Society: Churches of Christ](https://discipleshistory.org/wiki/churches-of-christ/). This shift was controversial, with leaders like Daniel Sommer and Carl Ketcherside asserting that preaching should be a communal activity, reflecting ongoing debates about the structure of ministry.